name: Build app
on: [push, pull_request, release]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.4'

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install ldid
      run: brew install ldid

    - name: Get dependencies
      run: flutter pub get

    - name: Build on iOS
      run: flutter build ios --release --no-codesign
    
    - name: Make IPA
      run: |
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa

    - uses: actions/upload-artifact@v2
      with:
        name: otpapp-artifact
        path: |
          Payload.ipa
